version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - run: |
          function cleanup()
          {
              echo "Clean up on aisle ${CIRCLE_BRANCH}..."
          }

          trap cleanup EXIT
          
          sleep 10
          echo "slept 10"
          
          sleep 10
          echo "slept another 30"
