version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - run: |
          function cleanup()
          {
              echo "Clean up on aisle 5..."
          }

          trap cleanup EXIT
          
          sleep 30
          echo "slept 30"
          
          sleep 30
          echo "slept another 30"
